---
- name: Check glance containers
  become: true
  #kolla_docker:
  containers.podman.podman_container:
    #action: "compare_container"
    #common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(omit) }}"
    environment: 
      "{{ item.value.environment | default(omit) }}"
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    volumes: "{{ item.value.volumes|reject('equalto', '')|list }}"
   # dimensions: "{{ item.value.dimensions }}"
    healthcheck: "{{ item.value.healthcheck | default(omit) }}"
    network: "host"
  when:
    - item.value.host_in_groups | bool
    - item.value.enabled | bool
  with_dict: "{{ glance_services }}"
  notify:
    - "Restart {{ item.key }} container"
