---
- name: Check neutron containers
  become: true
  #kolla_docker:
  containers.podman.podman_container:
    #action: "compare_container"
    #common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes }}"
    network: "host"
    #dimensions: "{{ item.value.dimensions }}"
    environment: 
      "{{ item.value.environment | default(omit) }}"
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    healthcheck: "{{ item.value.healthcheck | default(omit) }}"
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ neutron_services }}"
  #notify:
  #  - "Restart {{ item.key }} container"
