---
- name: Check haproxy containers
  become: true
  #kolla_docker:
  containers.podman.podman_container:
    #action: "compare_container"
    #common_options: "{{ docker_common_options }}"
    network: "host"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    #dimensions: "{{ item.value.dimensions }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    env:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ haproxy_services }}"
  #notify:
  #  - "Restart {{ item.key }} container"
