---
- name: Check heat containers
  become: true
  #kolla_docker:
  containers.podman.podman_container:
    #action: "compare_container"
    #common_options: "{{ docker_common_options }}"
    state: present
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes|reject('equalto', '')|list }}"
    dimensions: "{{ item.value.dimensions }}"
    healthcheck: "{{ item.value.healthcheck | default(omit) }}"
    network: "host"
    env:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ heat_services }}"
  #notify:
  #  - "Restart {{ item.key }} container"
