---
- name: Restart chrony container
  vars:
    service_name: "chrony"
    service: "{{ chrony_services[service_name] }}"
  become: true
  #kolla_docker:
  #  action: "recreate_or_restart_container"
  #  common_options: "{{ docker_common_options }}"
  containers.podman.podman_container:
    restart: yes
    privileged: "{{ service.privileged }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    env: 
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    #dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"
